- hosts: backend
  become: yes
  vars_files:
    - group_vars/all.yml
  vars:
    app_user: azureuser
    app_dir: /opt/pubment
    container_name: pubment-backend
    image_name: pubment-server
  tasks:
    - name: Add GPG key for libcontainers (Podman) repo
      apt_key:
        url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key
        state: present

    - name: Update apt cache and upgrade
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - curl
          - git
          - build-essential
          - ufw
          - podman
        state: present

    - name: Install Caddy
      shell: |
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        apt update
        apt install caddy -y
      args:
        creates: /usr/bin/caddy

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'

    - name: Clone repository
      git:
        repo: 'https://github.com/hammadmajid/pubment.git'
        dest: "{{ app_dir }}/app"
        version: main
        force: yes
      become_user: "{{ app_user }}"

    - name: Set ownership of application directory
      file:
        path: "{{ app_dir }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes

    - name: Create .env file from template
      template:
        src: templates/env.j2
        dest: "{{ app_dir }}/app/.env"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0600'

    - name: Stop and remove existing container
      shell: podman stop {{ container_name }} && podman rm {{ container_name }} || true
      become_user: "{{ app_user }}"
      ignore_errors: yes

    - name: Build image
      shell: podman build -t {{ image_name }} -f apps/server/Dockerfile .
      args:
        chdir: "{{ app_dir }}/app"
      become_user: "{{ app_user }}"

    - name: Run container in detached mode
      shell: |
        podman run -d \
          --name {{ container_name }} \
          --env-file {{ app_dir }}/app/.env \
          -p 3000:3000 \
          --restart=always \
          {{ image_name }}
      become_user: "{{ app_user }}"

    - name: Configure UFW - allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Configure UFW - allow HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Configure UFW - allow HTTPS
      ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Configure UFW - allow internal traffic on port 3000
      ufw:
        rule: allow
        port: 3000
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Configure Caddy reverse proxy
      copy:
        dest: /etc/caddy/Caddyfile
        content: |
          api.pubment.xyz {
              reverse_proxy localhost:3000

              # Enable CORS headers
              header {
                  Access-Control-Allow-Origin "https://pubment.xyz"
                  Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
                  Access-Control-Allow-Headers "Content-Type, Authorization"
                  Access-Control-Allow-Credentials "true"
              }

              # Handle preflight requests
              @options method OPTIONS
              respond @options 200
          }
      notify:
        - restart caddy

    - name: Enable and start Caddy service
      systemd:
        name: caddy
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: restart caddy
      systemd:
        name: caddy
        state: restarted
