- hosts: frontend
  become: yes
  vars_files:
    - vault.yml
    - frontend_vars.yml
  tasks:
    - name: Update apt cache and upgrade
      apt: update_cache=yes upgrade=dist

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Clone repository
      git:
        repo: 'https://github.com/hammadmajid/pubment.git'
        dest: /opt/pubment
        version: main

    - name: Create client .env
      copy:
        dest: /opt/pubment/apps/client/.env
        content: |
          API_BASE_URL=http://{{ backend_private_ip }}:3000
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Build client Docker image
      shell: docker build --file apps/client/Dockerfile -t pubment-client .
      args:
        chdir: /opt/pubment

    - name: Run client container
      docker_container:
        name: pubment-client
        image: pubment-client
        restart_policy: always
        env_file: /opt/pubment/apps/client/.env
        ports:
          - "3000:3000"
        state: started

    - name: Install Caddy
      apt:
        deb: https://github.com/caddyserver/caddy/releases/download/v2.7.6/caddy_2.7.6_linux_amd64.deb

    - name: Configure Caddyfile
      copy:
        dest: /etc/caddy/Caddyfile
        content: |
          pubment.xyz {
            reverse_proxy localhost:3000
            encode gzip
            header {
              Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
              X-Content-Type-Options "nosniff"
              X-Frame-Options "DENY"
              X-XSS-Protection "1; mode=block"
              Referrer-Policy "no-referrer-when-downgrade"
            }
            @http {
              protocol http
            }
            redir @http https://{host}{uri}
          }
        owner: root
        group: root
        mode: '0644'

    - name: Restart Caddy
      service:
        name: caddy
        state: restarted
        enabled: yes